name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🪲 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: "chore"
    files:
      - "*.md"
      - ".github/*"
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/i"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/i'
version-resolver:
  major:
    labels:
      - "major-release"
  minor:
    labels:
      - "minor-release"
  patch:
    labels:
      - "patch-release"
  default: patch
template: |
  ## Changes since $PREVIOUS_TAG

  $CHANGES
